from model.HPNet import HPNet
from model.HPNet_pathmask import HPNet_PathMaskSmall
from model.HPNet_pathmask_steplr import HPNet_PathMaskSmall_StepLR
from model.HPNet_dropkeybigger_steplr import HPNet_DropKeyBigger_StepLR
from model.HPNet_dropkey_steplr import HPNet_DropKey_StepLR
from model.HPNet_dropkeybigger2layer_steplr import HPNet_DropKeyBigger2Layer_StepLR
from model.HPNet_dropkeybigger22layer_steplr import HPNet_DropKeyBigger22Layer_StepLR
from model.HPNet_structuredropkeybigger1layer_steplr import HPNet_StructureDropKeyBigger1Layer_StepLR
from model.HPNet_structuredropkeybigger1layer_steplr_6_20 import HPNet_StructureDropKeyBigger1Layer_StepLR_6_20
from model.HPNet_structuredropkeybigger1layer_steplr_6_24 import HPNet_StructureDropKeyBigger1Layer_StepLR_6_24
from model.HPNet_structuredropkeybigger1layer_steplr_6_29 import HPNet_StructureDropKeyBigger1Layer_StepLR_6_29

from model.HPNet_structureIncreasedDropKeyBigger1Layer_steplr_6_24 import HPNet_StructureIncreasedDropKeyBigger1Layer_StepLR_6_24
from model.HPNet_structureIncreasedDropKeyBigger1Layer_BigR_steplr_6_24 import HPNet_StructureIncreasedDropKeyBigger1Layer_BigR_StepLR_6_24
from model.HPNet_structureIncreasedDropKeyBigger2Layer_steplr_6_24 import  HPNet_StructureIncreasedDropKeyBigger2Layer_StepLR_6_24

from model.HPNet_MoAstructureIncreasedDropKeyBigger1Layer_steplr_6_24 import HPNet_MoAStructureIncreasedDropKeyBigger1Layer_StepLR_6_24
from model.HPNet_MoAstructureIncreasedSoftDropKeyBigger1Layer_steplr_6_24 import HPNet_MoAStructureIncreasedSoftDropKeyBigger1Layer_StepLR_6_24


from model.HPNet_MoA1Layer_steplr_6_24 import HPNet_MoA1Layer_StepLR_6_24