from layers.graph_attention import GraphAttention
from layers.two_layer_mlp import TwoLayerMLP
from layers.SpaceMaskGraphAttention import SpaceMaskGraphAttention
from layers.KeyDropAttention import KeyDropGraphAttention
from layers.StructureKeyDropAttention import StructureKeyDropGraphAttention
from layers.StructureIncreaseKeyDropAttention import StructureIncreasedKeyDropGraphAttention
from layers.StructureIncreaseKeyDropAttention_BigR import StructureIncreasedKeyDropGraphAttention_BigR
from layers.MoAStructureIncreasedKeyDropAttention import MoAStructureIncreasedKeyDropGraphAttention
from layers.MoAStructureIncreasedSoftKeyDropAttention import MoAStructureIncreasedSoftKeyDropGraphAttention


from layers.graph_mosa_adaptive_attention_attgete import GraphAttentionAdaptiveMoSAAttGate
from layers.graph_attention_return_weight import GraphAttentionReturenW