from modules.backbone import Backbone
from modules.map_encoder import MapEncoder
from modules.backbone_pathmask import Backbone_PathMask
from modules.backbone_dropkey_bigger   import Backbone_DropKey_Bigger
from modules.backbone_dropkey  import Backbone_DropKey
from modules.backbone_dropkey_bigger_2layer  import Backbone_DropKey_Bigger2layer
from modules.backbone_dropkey_bigger2_2layer import Backbone_DropKey_Bigger22layer
from modules.backbone_structuredropkey_bigger_1layer import Backbone_StructureDropKey_Bigger1layer
from modules.backbone_structuredropkey_bigger_1layer_6_20 import Backbone_StructureDropKey_Bigger1layer_6_20
from modules.backbone_structuredropkey_bigger_1layer_6_24 import Backbone_StructureDropKey_Bigger1layer_6_24
from modules.backbone_structuredropkey_bigger_1layer_6_29 import Backbone_StructureDropKey_Bigger1layer_6_29
from modules.backbone_structureIncreaseddropkey_bigger_1layer_6_24 import Backbone_StructureIncreasedDropKey_Bigger1layer_6_24
from modules.backbone_structureIncreaseddropkey_bigger_2layer_6_24 import Backbone_StructureIncreasedDropKey_Bigger2layer_6_24


from modules.backbone_structureIncreaseddropkey_BigR_bigger_1layer_6_24 import Backbone_StructureIncreasedDropKey_BigR_Bigger1layer_6_24
from modules.backbone_MoAstructureIncreaseddropkey_bigger_1layer_6_24 import Backbone_MoAStructureIncreasedDropKey_Bigger1layer_6_24


from modules.backbone_MoAstructureIncreasedSoftdropkey_bigger_1layer_6_24 import Backbone_MoAStructureIncreasedSoftDropKey_Bigger1layer_6_24
from modules.backbone_MoA_bigger_1layer_6_24 import Backbone_MoA_Bigger1layer_6_24
from modules.backbone_static_attention import Backbone_Static